# Generated by Django 5.0.6 on 2024-09-12 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0009_company_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('office_location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('form', models.DateField()),
                ('to', models.DateField()),
                ('box', models.BooleanField(blank=True, null=True)),
                ('education', models.CharField(max_length=200)),
                ('facebookLink', models.CharField(max_length=200)),
                ('resume', models.ImageField(upload_to='resume')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
