# Generated by Django 5.0.6 on 2024-09-25 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_alter_apply_status'),
        ('place', '0003_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='Browse_cetagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.browse_cetagory'),
        ),
    ]
