# Generated by Django 5.0.6 on 2024-09-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_apply_browse_cetagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='Browse_cetagory',
        ),
    ]
