# Generated by Django 5.0.6 on 2024-09-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_remove_apply_browse_cetagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
