# Generated by Django 5.0.6 on 2024-09-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0007_alter_apply_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
