# Generated by Django 5.0.6 on 2024-10-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0009_alter_apply_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='description',
        ),
    ]
