# Generated by Django 5.0.6 on 2024-10-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0011_alter_apply_company_alter_apply_office_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='form',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
