# Generated by Django 5.0.6 on 2024-10-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0012_alter_apply_form_alter_apply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='form',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='to',
        ),
    ]
