# Generated by Django 5.0.6 on 2024-09-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_model',
            name='message_ss',
        ),
    ]
