# Generated by Django 5.0.6 on 2024-09-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_model_message_ss'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_leaders',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
