# Generated by Django 5.0.6 on 2024-09-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_position_our_leaders_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_model',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact_model',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
