# Generated by Django 5.0.6 on 2024-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_contact_model_phone_contact_model_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_model',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
