# Generated by Django 5.0.6 on 2024-09-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_register_model_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='slug',
        ),
    ]
