# Generated by Django 5.0.6 on 2024-09-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_model',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='country',
        ),
    ]
