# Generated by Django 5.0.6 on 2024-09-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='address',
        ),
    ]
