# Generated by Django 5.0.6 on 2024-09-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_job_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
