# Generated by Django 5.0.6 on 2024-09-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
