# Generated by Django 5.0.6 on 2024-09-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
