# Generated by Django 5.0.6 on 2024-09-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='application_date',
            new_name='application_deadline',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='published_date',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_information',
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
