# Generated by Django 5.0.6 on 2024-09-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_company_remove_job_company_name_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
