# Generated by Django 5.0.6 on 2024-09-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_remove_job_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.TextField(),
        ),
    ]
