# Generated by Django 5.0.6 on 2024-09-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_job_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Male/Female', 'Male/Female'), ('Others', 'Others')], max_length=30),
        ),
    ]
