# Generated by Django 5.0.6 on 2024-09-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_experience_alter_job_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
