# Generated by Django 5.0.6 on 2024-09-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_job_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_status',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Internship', 'Internship')], max_length=100),
        ),
    ]
