# Generated by Django 5.0.6 on 2024-09-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_job_office_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_on',
        ),
    ]
